# Generated by Django 4.0.4 on 2022-06-02 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M0',
            fields=[
                ('m0_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M1',
            fields=[
                ('m1_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.food')),
                ('m0_a_pk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='a', to='testapp.m0')),
                ('m1_a_pk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.m1')),
            ],
        ),
        migrations.CreateModel(
            name='M2',
            fields=[
                ('m2_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('m0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.m0')),
            ],
        ),
        migrations.AddField(
            model_name='m1',
            name='m1',
            field=models.ManyToManyField(through='testapp.M3', to='testapp.m0'),
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.food')),
            ],
        ),
    ]
