# Generated by Django 4.0.4 on 2022-06-02 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_m3_m0_b_pk_alter_m3_m1_a_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m3',
            name='m0_a_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.m0'),
        ),
    ]
