from enum import Enum

IS_ERROR = True

class CodeMessageEnum(Enum):
    '''
    狀態碼 int
    訊息 str
    is_error bool
    '''  
    ADD_HOSPITAL_SUCCESS = (710, '醫院註冊成功', not IS_ERROR)
    ADD_HOSPITAL_FAILED_BY_FORMAT = (810, '醫院註冊格式不符', IS_ERROR)
    ADD_EMPLOYEE_SUCCESS = (711, '員工註冊成功', not IS_ERROR)
    ADD_EMPLOYEE_FAILED_BY_FORMAT = (811, '格式不符', IS_ERROR)
    ADD_EMPLOYEE_FAILED_BY_HOSPITAL_ID_NOT_EXIST = (812, '醫院ID不存在', IS_ERROR)
    = (723, '取得醫院資訊', not IS_ERROR)
    = (846, '沒有醫院資訊', IS_ERROR)
    = (712, '排班成功', not IS_ERROR)
    = (813, '排班格式不符', IS_ERROR)
    = (847, '該員工已在同日排班', IS_ERROR)
    = (724, '取得員工資訊', not IS_ERROR)
    = (848, '沒有員工資訊', IS_ERROR)
    = (713, '新增寵物品種成功', not IS_ERROR)
    = (815, '寵物品種格式不符', IS_ERROR)
    = (725, '取得寵物品種資訊', not IS_ERROR)
    = (849, '沒有寵物品種資訊', IS_ERROR)
    = (714, '預約成功', not IS_ERROR)
    = (816, '預約格式不符', IS_ERROR)
    = (817, '該datetime沒有人上班', IS_ERROR)
    = (818, '寵物ID不存在', IS_ERROR)
    = (819, '醫院ID不存在', IS_ERROR)
    = (715, '寵物主人建檔成功', not IS_ERROR)
    = (820, '寵物主人建檔格式不符', IS_ERROR)
    = (821, '品種ID不存在', IS_ERROR)
    = (726, '取得寵物主人資訊', not IS_ERROR)
    = (850, '沒有寵物主人資訊', IS_ERROR)
    = (730, '取得主人資訊', not IS_ERROR)
    = (854, '沒有主人資訊', IS_ERROR)
    = (716, '主人新增寵物成功', not IS_ERROR)
    = (822, '主人新增寵物格式不符', IS_ERROR)
    = (823, '主人ID不存在', IS_ERROR)
    = (824, '品種ID不存在', IS_ERROR)
    = (727, '取得寵物資訊', not IS_ERROR)
    = (851, '沒有寵物資訊', IS_ERROR)
    = (717, '寵物換主人成功', not IS_ERROR)
    = (825, '寵物換主人格式不符', IS_ERROR)
    = (826, '寵物ID不存在', IS_ERROR)
    = (718, '寵物換主人成功', not IS_ERROR)
    = (827, '寵物換主人格式不符', IS_ERROR)
    = (828, '顧客ID不存在', IS_ERROR)
    = (829, '寵物ID不存在', IS_ERROR)
    = (719, '新增醫療項目成功', not IS_ERROR)
    = (830, '醫療項目格式不符', IS_ERROR)
    = (728, '取得醫療項目資訊', not IS_ERROR)
    = (852, '沒有醫療項目資訊', IS_ERROR)
    = (720, '看診紀錄成功', not IS_ERROR)
    = (831, '看診紀錄格式不符', IS_ERROR)
    = (832, '寵物ID不存在', IS_ERROR)
    = (833, '獸醫ID不存在', IS_ERROR)
    = (834, '獸醫ID填入的ID的職業並不是獸醫', IS_ERROR)
    = (835, '獸醫助理ID不存在', IS_ERROR)
    = (836, '獸醫助理ID填入的ID的職業並不是獸醫助理', IS_ERROR)
    = (837, '醫療項目ID不存在', IS_ERROR)
    = (721, '新增美容項目成功', not IS_ERROR)
    = (838, '美容項目格式不符', IS_ERROR)
    = (729, '取得美容項目資訊', not IS_ERROR)
    = (853, '沒有美容項目資訊', IS_ERROR)
    = (722, '看診紀錄成功', not IS_ERROR)
    = (839, '看診紀錄格式不符', IS_ERROR)
    = (840, '寵物ID不存在', IS_ERROR)
    = (841, '美容師ID不存在', IS_ERROR)
    = (842, '美容師ID填入的ID的職業並不是獸醫', IS_ERROR)
    = (843, '美容助理ID不存在', IS_ERROR)
    = (844, '助理ID填入的ID的職業並不是美容助理', IS_ERROR)
    = (845, '美容項目ID不存在', IS_ERROR)